language: nodejs
dist: trusty
addons:
  sonarcloud:
    organization: "mkmonreal"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
